apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: springboot-app  # ✅ This must be fixed
          image: springboot-app
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
